/**
 * Kho từ cho Wordle từ vựng — tiếng Anh 5 chữ cái, mức A2–B1 (VSTEP).
 *
 * [từ, nghĩa tiếng Việt] — từ ĐỀ (hàng ngày chọn từ đây) và cũng là gợi ý học.
 * Người chơi được gõ BẤT KỲ từ 5 chữ nào (không khoán từ điển) để không phải
 * "đoán trong danh sách" — đúng tinh thần học từ vựng.
 */

export type WordEntry = readonly [word: string, meaning: string]

export const WORDS: readonly WordEntry[] = [
  ['about', 'về, khoảng'],
  ['above', 'phía trên'],
  ['actor', 'diễn viên'],
  ['admit', 'thừa nhận'],
  ['adopt', 'nhận nuôi; áp dụng'],
  ['adult', 'người lớn'],
  ['after', 'sau'],
  ['again', 'lại, lần nữa'],
  ['agent', 'đại lý, nhân viên'],
  ['agree', 'đồng ý'],
  ['ahead', 'phía trước'],
  ['alarm', 'báo động, chuông'],
  ['album', 'album, tập ảnh'],
  ['alert', 'cảnh báo, tỉnh táo'],
  ['alien', 'người ngoài hành tinh'],
  ['alike', 'giống nhau'],
  ['alive', 'còn sống'],
  ['allow', 'cho phép'],
  ['alone', 'một mình'],
  ['along', 'dọc theo'],
  ['alter', 'thay đổi'],
  ['among', 'trong số'],
  ['anger', 'sự giận dữ'],
  ['angle', 'góc'],
  ['angry', 'tức giận'],
  ['apart', 'riêng biệt'],
  ['apple', 'quả táo'],
  ['apply', 'áp dụng; nộp đơn'],
  ['arena', 'đấu trường'],
  ['argue', 'tranh luận'],
  ['arise', 'phát sinh'],
  ['array', 'mảng, một dãy'],
  ['aside', 'sang một bên'],
  ['asset', 'tài sản'],
  ['audio', 'âm thanh'],
  ['avoid', 'tránh'],
  ['awake', 'tỉnh thức'],
  ['award', 'giải thưởng'],
  ['aware', 'nhận thức được'],
  ['badly', 'tệ, một cách tồi'],
  ['baker', 'thợ làm bánh'],
  ['basic', 'cơ bản'],
  ['basis', 'cơ sở'],
  ['beach', 'bãi biển'],
  ['begin', 'bắt đầu'],
  ['being', 'tồn tại'],
  ['below', 'phía dưới'],
  ['bench', 'ghế dài'],
  ['birth', 'sự ra đời'],
  ['black', 'màu đen'],
  ['blade', 'lưỡi dao'],
  ['blame', 'đổ lỗi'],
  ['blank', 'trống, trắng'],
  ['blast', 'vụ nổ'],
  ['blend', 'pha trộn'],
  ['bless', 'ban phước'],
  ['blind', 'mù'],
  ['block', 'chặn; khối'],
  ['blood', 'máu'],
  ['board', 'bảng; lên tàu'],
  ['boost', 'tăng cường'],
  ['booth', 'gian hàng'],
  ['bound', 'ràng buộc; chắc chắn'],
  ['brain', 'não'],
  ['brand', 'nhãn hiệu'],
  ['bread', 'bánh mì'],
  ['break', 'phá vỡ; nghỉ giải lao'],
  ['breed', 'giống; gây ra'],
  ['brief', 'ngắn gọn'],
  ['bring', 'mang'],
  ['broad', 'rộng'],
  ['broke', 'đã vỡ; trắng tay'],
  ['brown', 'màu nâu'],
  ['build', 'xây dựng'],
  ['built', 'đã xây'],
  ['buyer', 'người mua'],
  ['cable', 'dây cáp'],
  ['candy', 'kẹo'],
  ['cargo', 'hàng hóa'],
  ['carry', 'mang, kéo theo'],
  ['cause', 'nguyên nhân'],
  ['chain', 'chuỗi'],
  ['chair', 'ghế'],
  ['charm', 'sức hút'],
  ['chart', 'biểu đồ'],
  ['chase', 'đuổi theo'],
  ['cheap', 'rẻ'],
  ['check', 'kiểm tra'],
  ['cheek', 'má'],
  ['cheer', 'cổ vũ'],
  ['chess', 'cờ vua'],
  ['chest', 'ngực; rương'],
  ['chief', 'trưởng, chủ'],
  ['child', 'đứa trẻ'],
  ['chill', 'lạnh; thư giãn'],
  ['china', 'sứ'],
  ['chose', 'đã chọn'],
  ['civic', 'thuộc công dân'],
  ['civil', 'dân sự'],
  ['claim', 'tuyên bố'],
  ['class', 'lớp; giai cấp'],
  ['clean', 'sạch'],
  ['clear', 'rõ ràng'],
  ['click', 'nhấp chuột'],
  ['cliff', 'vách đá'],
  ['climb', 'leo'],
  ['clock', 'đồng hồ'],
  ['close', 'đóng; gần'],
  ['cloth', 'vải'],
  ['cloud', 'mây'],
  ['coach', 'huấn luyện viên'],
  ['coast', 'bờ biển'],
  ['color', 'màu'],
  ['comic', 'truyện tranh'],
  ['coral', 'san hô'],
  ['could', 'có thể (quá khứ)'],
  ['count', 'đếm'],
  ['court', 'sân; tòa án'],
  ['cover', 'che phủ'],
  ['crack', 'vết nứt'],
  ['craft', 'thủ công; nghề'],
  ['crash', 'va chạm'],
  ['cream', 'kem'],
  ['crime', 'tội phạm'],
  ['crisp', 'giòn'],
  ['cross', 'băng qua'],
  ['crowd', 'đám đông'],
  ['crown', 'vương miện'],
  ['curve', 'đường cong'],
  ['cycle', 'chu kỳ'],
  ['daily', 'hằng ngày'],
  ['dance', 'nhảy múa'],
  ['death', 'cái chết'],
  ['debut', 'ra mắt'],
  ['delay', 'trì hoãn'],
  ['dense', 'dày đặc'],
  ['depth', 'độ sâu'],
  ['digit', 'chữ số'],
  ['dirty', 'bẩn'],
  ['doubt', 'nghi ngờ'],
  ['dozen', 'tá (12)'],
  ['draft', 'bản nháp'],
  ['drama', 'kịch, kịch tính'],
  ['dream', 'giấc mơ'],
  ['drink', 'uống'],
  ['drive', 'lái xe'],
  ['eager', 'háo hức'],
  ['early', 'sớm'],
  ['earth', 'trái đất'],
  ['eight', 'số tám'],
  ['elite', 'tinh hoa'],
  ['empty', 'rỗng'],
  ['enemy', 'kẻ thù'],
  ['enjoy', 'tận hưởng'],
  ['enter', 'nhập, đi vào'],
  ['equal', 'bằng nhau'],
  ['error', 'lỗi'],
  ['essay', 'bài luận'],
  ['event', 'sự kiện'],
  ['every', 'mỗi'],
  ['exact', 'chính xác'],
  ['exist', 'tồn tại'],
  ['extra', 'thêm, ngoài'],
  ['faith', 'niềm tin'],
  ['false', 'sai'],
  ['fault', 'lỗi, khuyết điểm'],
  ['fence', 'hàng rào'],
  ['ferry', 'tàu phà'],
  ['fever', 'cơn sốt'],
  ['field', 'cánh đồng; lĩnh vực'],
  ['fight', 'chiến đấu'],
  ['final', 'cuối cùng'],
  ['first', 'đầu tiên'],
  ['flame', 'ngọn lửa'],
  ['flash', 'ánh chớp'],
  ['fleet', 'đội tàu, đội xe'],
  ['float', 'nổi'],
  ['flood', 'trận lũ'],
  ['floor', 'sàn nhà'],
  ['flour', 'bột mì'],
  ['fluid', 'chất lỏng'],
  ['focus', 'tập trung'],
  ['force', 'lực, ép'],
  ['found', 'đã tìm thấy'],
  ['frame', 'khung'],
  ['fresh', 'tươi mới'],
  ['front', 'phía trước'],
  ['fruit', 'trái cây'],
  ['fully', 'hoàn toàn'],
  ['funny', 'buồn cười'],
  ['ghost', 'con ma'],
  ['giant', 'khổng lồ'],
  ['glass', 'thủy tinh'],
  ['globe', 'quả địa cầu'],
  ['glory', 'vinh quang'],
  ['glove', 'găng tay'],
  ['going', 'đang đi'],
  ['grace', 'duyên dáng'],
  ['grade', 'điểm; hạng'],
  ['grain', 'hạt (lúa)'],
  ['grand', 'hùng vĩ'],
  ['grant', 'cấp, trao'],
  ['grave', 'mộ; nghiêm trọng'],
  ['great', 'vĩ đại'],
  ['green', 'màu xanh lá'],
  ['greet', 'chào'],
  ['grief', 'nỗi buồn'],
  ['grill', 'nướng'],
  ['group', 'nhóm'],
  ['grown', 'đã lớn lên'],
  ['guard', 'canh gác'],
  ['guess', 'suy đoán'],
  ['guest', 'khách'],
  ['guide', 'hướng dẫn'],
  ['happy', 'hạnh phúc'],
  ['harsh', 'khắc nghiệt'],
  ['heart', 'trái tim'],
  ['heavy', 'nặng'],
  ['hobby', 'sở thích'],
  ['honey', 'mật ong'],
  ['honor', 'danh dự'],
  ['horse', 'con ngựa'],
  ['hotel', 'khách sạn'],
  ['house', 'ngôi nhà'],
  ['human', 'con người'],
  ['humor', 'sự hài hước'],
  ['hurry', 'sự vội vã'],
  ['ideal', 'lý tưởng'],
  ['image', 'hình ảnh'],
  ['imply', 'ngụ ý'],
  ['index', 'chỉ mục'],
  ['inner', 'bên trong'],
  ['input', 'đầu vào'],
  ['issue', 'vấn đề'],
  ['jelly', 'thạch'],
  ['joint', 'khớp; chung'],
  ['judge', 'thẩm phán; phán xét'],
  ['known', 'được biết đến'],
  ['label', 'nhãn'],
  ['large', 'lớn'],
  ['later', 'sau đó'],
  ['laugh', 'cười'],
  ['layer', 'lớp'],
  ['learn', 'học'],
  ['least', 'ít nhất'],
  ['leave', 'rời đi; lá'],
  ['legal', 'hợp pháp'],
  ['level', 'cấp độ'],
  ['light', 'ánh sáng; nhẹ'],
  ['limit', 'giới hạn'],
  ['local', 'thuộc địa phương'],
  ['logic', 'logic'],
  ['loose', 'lỏng'],
  ['lucky', 'may mắn'],
  ['lunch', 'bữa trưa'],
  ['magic', 'ma thuật'],
  ['major', 'chính; chuyên ngành'],
  ['match', 'trận đấu; khớp'],
  ['maybe', 'có lẽ'],
  ['mayor', 'thị trưởng'],
  ['meant', 'đã có nghĩa là'],
  ['media', 'truyền thông'],
  ['metal', 'kim loại'],
  ['might', 'có thể'],
  ['minor', 'nhỏ; vị thành niên'],
  ['minus', 'phép trừ'],
  ['mixed', 'hỗn hợp'],
  ['model', 'mô hình; người mẫu'],
  ['money', 'tiền'],
  ['month', 'tháng'],
  ['moral', 'đạo đức'],
  ['motor', 'động cơ'],
  ['mount', 'leo; ngọn'],
  ['mouse', 'con chuột'],
  ['mouth', 'cái miệng'],
  ['movie', 'bộ phim'],
  ['music', 'âm nhạc'],
  ['naive', 'ngây thơ'],
  ['nerve', 'dây thần kinh'],
  ['never', 'không bao giờ'],
  ['newly', 'mới đây'],
  ['night', 'đêm'],
  ['noble', 'cao quý'],
  ['noise', 'tiếng ồn'],
  ['north', 'phía bắc'],
  ['noted', 'nổi tiếng'],
  ['novel', 'tiểu thuyết; mới lạ'],
  ['nurse', 'y tá'],
  ['occur', 'xảy ra'],
  ['ocean', 'đại dương'],
  ['offer', 'đề nghị'],
  ['often', 'thường xuyên'],
  ['onion', 'củ hành'],
  ['orbit', 'quỹ đạo'],
  ['order', 'thứ tự; đặt hàng'],
  ['organ', 'cơ quan; đàn ống'],
  ['other', 'khác'],
  ['ought', 'nên (khuyết thiếu)'],
  ['outer', 'bên ngoài'],
  ['owner', 'chủ sở hữu'],
  ['paint', 'sơn; vẽ'],
  ['panel', 'tấm; hội đồng'],
  ['paper', 'giấy'],
  ['party', 'bữa tiệc; đảng'],
  ['peace', 'hòa bình'],
  ['pearl', 'ngọc trai'],
  ['phase', 'giai đoạn'],
  ['phone', 'điện thoại'],
  ['photo', 'ảnh chụp'],
  ['piece', 'mảnh, miếng'],
  ['pilot', 'phi công'],
  ['pitch', 'ném; cao độ'],
  ['pizza', 'bánh pizza'],
  ['place', 'nơi, địa điểm'],
  ['plain', 'đồng bằng; đơn giản'],
  ['plane', 'máy bay'],
  ['plant', 'cây; nhà máy'],
  ['plate', 'cái đĩa'],
  ['point', 'điểm; chỉ'],
  ['polar', 'thuộc cực'],
  ['porch', 'hiên nhà'],
  ['pound', 'bảng Anh; đập'],
  ['power', 'sức mạnh'],
  ['press', 'báo chí; nhấn'],
  ['price', 'giá cả'],
  ['pride', 'niềm tự hào'],
  ['prime', 'chính; đẹp nhất'],
  ['print', 'in'],
  ['prize', 'giải thưởng'],
  ['proof', 'bằng chứng'],
  ['proud', 'tự hào'],
  ['prove', 'chứng minh'],
  ['queen', 'nữ hoàng'],
  ['quick', 'nhanh'],
  ['quiet', 'yên tĩnh'],
  ['radio', 'đài phát thanh'],
  ['raise', 'nâng lên'],
  ['range', 'dải; phạm vi'],
  ['rapid', 'nhanh, gấp'],
  ['ratio', 'tỉ lệ'],
  ['reach', 'chạm tới'],
  ['ready', 'sẵn sàng'],
  ['refer', 'tham chiếu'],
  ['reign', 'trị vì'],
  ['relax', 'thư giãn'],
  ['reply', 'trả lời'],
  ['right', 'đúng; bên phải'],
  ['rival', 'đối thủ'],
  ['river', 'dòng sông'],
  ['robot', 'rô-bốt'],
  ['rough', 'gồ ghề; thô ráp'],
  ['round', 'tròn; vòng'],
  ['route', 'tuyến đường'],
  ['royal', 'thuộc hoàng gia'],
  ['rural', 'thuộc nông thôn'],
  ['sadly', 'buồn bã'],
  ['salad', 'món xa lách'],
  ['sales', 'doanh số'],
  ['salon', 'tiệm làm đẹp'],
  ['sauce', 'nước sốt'],
  ['scale', 'quy mô; cân'],
  ['scare', 'làm sợ'],
  ['scene', 'cảnh, bối cảnh'],
  ['scope', 'phạm vi'],
  ['score', 'điểm số'],
  ['scout', 'trinh sát'],
  ['sense', 'giác quan; ý nghĩa'],
  ['serve', 'phục vụ'],
  ['seven', 'số bảy'],
  ['shade', 'bóng râm'],
  ['shake', 'lắc'],
  ['shape', 'hình dạng'],
  ['share', 'chia sẻ'],
  ['sharp', 'sắc, nhọn'],
  ['sheep', 'con cừu'],
  ['sheet', 'tờ (giấy)'],
  ['shelf', 'kệ'],
  ['shine', 'tỏa sáng'],
  ['shirt', 'áo sơ mi'],
  ['shock', 'cú sốc'],
  ['shore', 'bờ (biển)'],
  ['short', 'ngắn; thấp'],
  ['shown', 'đã được hiển thị'],
  ['sight', 'tầm mắt'],
  ['since', 'từ khi'],
  ['sixty', 'sáu mươi'],
  ['skill', 'kỹ năng'],
  ['skirt', 'váy'],
  ['sleep', 'ngủ'],
  ['slide', 'trượt; slide'],
  ['slope', 'con dốc'],
  ['small', 'nhỏ'],
  ['smart', 'thông minh'],
  ['smell', 'mùi; ngửi'],
  ['smile', 'nụ cười'],
  ['smoke', 'khói'],
  ['snack', 'đồ ăn nhẹ'],
  ['solar', 'thuộc mặt trời'],
  ['solid', 'rắn; vững'],
  ['solve', 'giải (bài toán)'],
  ['sound', 'âm thanh; khoẻ'],
  ['south', 'phía nam'],
  ['space', 'không gian'],
  ['spare', 'dự phòng'],
  ['speak', 'nói'],
  ['speed', 'tốc độ'],
  ['spell', 'đánh vần'],
  ['spend', 'dành, tiêu'],
  ['spice', 'gia vị'],
  ['split', 'chia, tách'],
  ['spoke', 'đã nói'],
  ['sport', 'thể thao'],
  ['staff', 'nhân viên'],
  ['stage', 'sân khấu; giai đoạn'],
  ['stand', 'đứng'],
  ['start', 'bắt đầu'],
  ['state', 'trạng thái; bang'],
  ['steak', 'thịt bít tết'],
  ['steep', 'dốc đứng'],
  ['stick', 'gậy; dính'],
  ['still', 'vẫn; tĩnh'],
  ['stone', 'viên đá'],
  ['store', 'cửa hàng; lưu'],
  ['storm', 'cơn bão'],
  ['story', 'câu chuyện'],
  ['stove', 'bếp'],
  ['straw', 'rơm; ống hút'],
  ['strip', 'dải; tước'],
  ['study', 'học, nghiên cứu'],
  ['stuff', 'thứ, đồ'],
  ['style', 'phong cách'],
  ['sugar', 'đường'],
  ['sunny', 'nắng ráo'],
  ['super', 'siêu, cực'],
  ['surge', 'tăng vọt'],
  ['sweet', 'ngọt'],
  ['swift', 'nhanh nhẹn'],
  ['table', 'cái bàn'],
  ['taken', 'đã lấy'],
  ['taste', 'vị; nếm'],
  ['teach', 'dạy'],
  ['teeth', 'răng (số nhiều)'],
  ['tenth', 'thứ mười'],
  ['thank', 'cảm ơn'],
  ['theme', 'chủ đề'],
  ['thick', 'dày'],
  ['thief', 'kẻ trộm'],
  ['thing', 'vật, thứ'],
  ['think', 'nghĩ'],
  ['third', 'thứ ba'],
  ['those', 'những (cái đó)'],
  ['three', 'số ba'],
  ['throw', 'ném'],
  ['tiger', 'con hổ'],
  ['tight', 'chặt'],
  ['timer', 'bộ đếm giờ'],
  ['title', 'tiêu đề'],
  ['toast', 'bánh nướng'],
  ['today', 'hôm nay'],
  ['token', 'dấu hiệu; token'],
  ['tooth', 'cái răng'],
  ['topic', 'chủ đề'],
  ['total', 'tổng'],
  ['touch', 'chạm'],
  ['tower', 'tòa tháp'],
  ['trace', 'dấu vết'],
  ['track', 'rãnh; theo dõi'],
  ['trade', 'buôn bán'],
  ['train', 'tàu; huấn luyện'],
  ['treat', 'đối xử; đãi'],
  ['trend', 'xu hướng'],
  ['trial', 'phiên tòa; thử'],
  ['tribe', 'bộ lạc'],
  ['trick', 'mẹo, trò'],
  ['truck', 'xe tải'],
  ['truly', 'thực sự'],
  ['trust', 'tin tưởng'],
  ['truth', 'sự thật'],
  ['twice', 'hai lần'],
  ['uncle', 'chú, bác'],
  ['under', 'dưới'],
  ['union', 'sự liên hiệp'],
  ['unity', 'sự thống nhất'],
  ['until', 'cho đến khi'],
  ['upper', 'phía trên'],
  ['urban', 'thuộc thành thị'],
  ['usage', 'cách dùng'],
  ['usual', 'như thường lệ'],
  ['valid', 'hợp lệ'],
  ['value', 'giá trị'],
  ['video', 'video'],
  ['viral', 'lan truyền'],
  ['virus', 'vi rút'],
  ['visit', 'thăm'],
  ['vital', 'sống còn'],
  ['vivid', 'sống động'],
  ['vocal', 'thuộc giọng nói'],
  ['voice', 'giọng nói'],
  ['wagon', 'xe ngựa; toa'],
  ['waste', 'lãng phí'],
  ['watch', 'đồng hồ đeo; xem'],
  ['water', 'nước'],
  ['whale', 'cá voi'],
  ['wheat', 'lúa mì'],
  ['wheel', 'bánh xe'],
  ['where', 'ở đâu'],
  ['which', 'cái nào'],
  ['while', 'trong khi'],
  ['white', 'màu trắng'],
  ['whole', 'toàn bộ'],
  ['whose', 'của ai'],
  ['width', 'chiều rộng'],
  ['world', 'thế giới'],
  ['worry', 'lo lắng'],
  ['worse', 'tệ hơn'],
  ['worst', 'tệ nhất'],
  ['worth', 'đáng giá'],
  ['would', 'sẽ (ở quá khứ)'],
  ['write', 'viết'],
  ['wrong', 'sai'],
  ['yield', 'năng suất; nhường'],
  ['young', 'trẻ'],
  ['youth', 'tuổi trẻ'],
  ['zebra', 'con ngựa vằn'],
]

/** Tra nghĩa của một từ (nếu có trong kho). */
export function meaningOf(word: string): string | undefined {
  return WORDS.find(([w]) => w === word)?.[1]
}
